#!/bin/bash
# ==============================================================================
# Test Database Setup Script for PostgreSQL 17 on SSH Server 'four'
# ==============================================================================
# This script creates a test database that mirrors production for E2E testing.
# Uses SSH to connect to postgres server and set up the test environment.

set -e  # Exit on any error

# Configuration
PG_HOST="four"
PG_PORT="5432"
PG_USER="postgres"
TEST_DB_NAME="pdf_to_markdown_mcp_test"
TEST_USER="test_user"
TEST_PASSWORD="test_password_e2e_$(date +%s)"  # Unique password per run

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}==============================================================================${NC}"
echo -e "${BLUE}Setting up test database for PDF to Markdown MCP E2E tests${NC}"
echo -e "${BLUE}==============================================================================${NC}"

# Function to run SQL commands via SSH
run_sql() {
    local sql="$1"
    local database="${2:-postgres}"

    ssh "$PG_HOST" "sudo -u postgres psql -d '$database' -c \"$sql\""
}

# Function to check if database exists
db_exists() {
    local db_name="$1"
    result=$(ssh "$PG_HOST" "sudo -u postgres psql -d postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='$db_name'\"")
    [[ "$result" == "1" ]]
}

# Function to check if user exists
user_exists() {
    local user_name="$1"
    result=$(ssh "$PG_HOST" "sudo -u postgres psql -d postgres -tAc \"SELECT 1 FROM pg_user WHERE usename='$user_name'\"")
    [[ "$result" == "1" ]]
}

echo -e "${YELLOW}Step 1: Checking PostgreSQL connection...${NC}"
if ssh "$PG_HOST" "sudo -u postgres psql -c '\\l'" > /dev/null 2>&1; then
    echo -e "${GREEN}✓ Successfully connected to PostgreSQL on $PG_HOST${NC}"
else
    echo -e "${RED}✗ Failed to connect to PostgreSQL on $PG_HOST${NC}"
    echo "Please ensure:"
    echo "  1. SSH access to '$PG_HOST' is working"
    echo "  2. PostgreSQL 17 is running"
    echo "  3. postgres user has sudo access"
    exit 1
fi

echo -e "${YELLOW}Step 2: Creating test user...${NC}"
if user_exists "$TEST_USER"; then
    echo -e "${YELLOW}  Test user '$TEST_USER' already exists, dropping and recreating...${NC}"
    run_sql "DROP USER IF EXISTS $TEST_USER CASCADE;"
fi

run_sql "CREATE USER $TEST_USER WITH PASSWORD '$TEST_PASSWORD';"
run_sql "ALTER USER $TEST_USER CREATEDB;"  # Allow creating databases for tests
echo -e "${GREEN}✓ Created test user '$TEST_USER'${NC}"

echo -e "${YELLOW}Step 3: Setting up test database...${NC}"
if db_exists "$TEST_DB_NAME"; then
    echo -e "${YELLOW}  Test database '$TEST_DB_NAME' already exists, dropping and recreating...${NC}"
    # Terminate active connections first
    run_sql "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='$TEST_DB_NAME' AND pid <> pg_backend_pid();"
    run_sql "DROP DATABASE IF EXISTS $TEST_DB_NAME;"
fi

run_sql "CREATE DATABASE $TEST_DB_NAME OWNER $TEST_USER;"
echo -e "${GREEN}✓ Created test database '$TEST_DB_NAME'${NC}"

echo -e "${YELLOW}Step 4: Setting up database permissions...${NC}"
run_sql "GRANT ALL PRIVILEGES ON DATABASE $TEST_DB_NAME TO $TEST_USER;" "postgres"
run_sql "GRANT ALL ON SCHEMA public TO $TEST_USER;" "$TEST_DB_NAME"
run_sql "GRANT ALL ON ALL TABLES IN SCHEMA public TO $TEST_USER;" "$TEST_DB_NAME"
run_sql "GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO $TEST_USER;" "$TEST_DB_NAME"
run_sql "GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO $TEST_USER;" "$TEST_DB_NAME"

# Set default privileges for future objects
run_sql "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $TEST_USER;" "$TEST_DB_NAME"
run_sql "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $TEST_USER;" "$TEST_DB_NAME"
run_sql "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO $TEST_USER;" "$TEST_DB_NAME"

echo -e "${GREEN}✓ Set up database permissions${NC}"

echo -e "${YELLOW}Step 5: Installing pgvector extension...${NC}"
if run_sql "CREATE EXTENSION IF NOT EXISTS vector;" "$TEST_DB_NAME" > /dev/null 2>&1; then
    echo -e "${GREEN}✓ pgvector extension installed${NC}"
else
    echo -e "${YELLOW}⚠ pgvector extension not available (this is OK for basic testing)${NC}"
fi

echo -e "${YELLOW}Step 6: Creating .env.test file...${NC}"
cat > .env.test << EOF
# Test Environment Configuration
# Generated by setup_test_database.sh on $(date)

# Test Database Configuration
TEST_DATABASE_URL=postgresql://$TEST_USER:$TEST_PASSWORD@$PG_HOST:$PG_PORT/$TEST_DB_NAME
TEST_DATABASE_URL_ASYNC=postgresql+asyncpg://$TEST_USER:$TEST_PASSWORD@$PG_HOST:$PG_PORT/$TEST_DB_NAME

# Database connection settings for tests
DB_HOST=$PG_HOST
DB_PORT=$PG_PORT
DB_NAME=$TEST_DB_NAME
DB_USER=$TEST_USER
DB_PASSWORD=$TEST_PASSWORD

# Test-specific settings
TEST_DB_POOL_SIZE=5
TEST_DB_MAX_OVERFLOW=2
TEST_DB_POOL_TIMEOUT=10
TEST_DB_CONNECT_TIMEOUT=5
TEST_DB_MAX_RETRIES=3

# Environment markers
ENVIRONMENT=test
TEST_ENVIRONMENT=true
DEBUG=true

# Mock settings for tests
TEST_MOCK_SERVICES=true
TEST_MOCK_MINERU=true
TEST_MOCK_EMBEDDINGS=true

# Test directories
TEST_INPUT_DIRECTORY=/tmp/test_pdf_input
TEST_OUTPUT_DIRECTORY=/tmp/test_pdf_output
TEST_TEMP_DIR=/tmp/test_pdf_temp
EOF

echo -e "${GREEN}✓ Created .env.test file with database credentials${NC}"

echo -e "${YELLOW}Step 7: Testing database connection...${NC}"
if run_sql "SELECT version();" "$TEST_DB_NAME" > /dev/null 2>&1; then
    echo -e "${GREEN}✓ Test database connection successful${NC}"
else
    echo -e "${RED}✗ Test database connection failed${NC}"
    exit 1
fi

echo -e "${YELLOW}Step 8: Verifying setup...${NC}"
echo -e "Database Info:"
run_sql "SELECT
    current_database() as database,
    current_user as user,
    inet_server_addr() as host,
    inet_server_port() as port;" "$TEST_DB_NAME"

# Check pgvector
echo -e "\nExtensions:"
run_sql "SELECT extname, extversion FROM pg_extension WHERE extname = 'vector';" "$TEST_DB_NAME" || echo "  pgvector: not installed"

echo -e "\n${GREEN}==============================================================================${NC}"
echo -e "${GREEN}✓ Test database setup completed successfully!${NC}"
echo -e "${GREEN}==============================================================================${NC}"

echo -e "\n${BLUE}Next steps:${NC}"
echo -e "1. Load the test environment: ${YELLOW}source .env.test${NC}"
echo -e "2. Run the E2E tests: ${YELLOW}pytest tests/integration/test_directory_mirroring_e2e.py -v${NC}"
echo -e "3. For verbose output: ${YELLOW}pytest tests/integration/test_directory_mirroring_e2e.py -v -s${NC}"

echo -e "\n${BLUE}Test Database Details:${NC}"
echo -e "  Host: $PG_HOST"
echo -e "  Port: $PG_PORT"
echo -e "  Database: $TEST_DB_NAME"
echo -e "  User: $TEST_USER"
echo -e "  Password: $TEST_PASSWORD"
echo -e "  Connection URL: postgresql://$TEST_USER:$TEST_PASSWORD@$PG_HOST:$PG_PORT/$TEST_DB_NAME"

echo -e "\n${YELLOW}Note: Test database credentials are saved in .env.test${NC}"
echo -e "${YELLOW}Keep this file secure and do not commit it to version control!${NC}"